# Generated by Django 4.2.3 on 2023-08-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50, null=True)),
                ('Phone_number', models.IntegerField()),
                ('Email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=16)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
